const auth = require("../controllers/adminController");
const authJwt = require("../middlewares/authJwt");
const router = require('express').Router();
router.post("/registration", auth.registration);
router.post("/login", auth.signIn);
router.put("/update", [authJwt.verifyToken], auth.update);
router.get("/getDoctor", auth.getDoctor);
router.get("/getApprovedDoctor", auth.getApprovedDoctor);
router.get("/getPatient",auth.getPatients);
router.get("/getAllDocument",[authJwt.verifyToken],auth.getDocument);
router.get('/getDocumentbyId/:id',authJwt.verifyToken,auth.getDocumentbyId);
router.put('/documentApprovedreject/:id',authJwt.verifyToken,auth.documentApprovedreject);
router.post('/addContact',authJwt.verifyToken,auth.addContact);
router.put('/editContact/:id',authJwt.verifyToken,auth.editContact);
router.delete('/deleteContact/:id',authJwt.verifyToken, auth.deleteContact);
router.get('/getcontact', auth.getcontact);
router.post("/createFaq", authJwt.verifyToken, auth.createFaq);
router.patch("/updatefaq/:id",authJwt.verifyToken, auth.updateFaq);
router.get("/getbyfaqId/:id", auth.getIdFaq);
router.delete("/deleteFaq/:id",authJwt.verifyToken,auth.deleteFaq);
router.get("/getAllFaq", auth.getFaq);
router.post("/createCategory",authJwt.verifyToken,auth.createCategory);
router.get("/category/:id", auth.getIdCategory);
router.patch("/udateCategory/:id",authJwt.verifyToken,auth.updateCategory);
router.get("/category", auth.getCategory);
router.delete("/category/:id",authJwt.verifyToken, auth.deleteCategory);
router.get("/subcategory/:id", auth.getIdSubCategory);
router.get("/subcategory", auth.getSubCategory);
router.post("/createSubcategory",authJwt.verifyToken,auth.createSubCategory);
router.patch("/subcategory/:id",authJwt.verifyToken,auth.updateSubCategory);
router.delete("/subcategory/:id",authJwt.verifyToken,auth.deleteSubCategory);
router.get('/help/:id', auth.getByIdhelpandSupport);
router.get('/help', auth.getAllHelpandSupport);
router.delete('/deleteHelp/:id', auth.DeleteHelpandSupport);
module.exports = router;
