const auth = require("../controllers/admin.Controller");
const authJwt = require("../middlewares/authJwt");
module.exports = (app) => {
        app.post("/api/v1/admin/registration", auth.registration);
        app.post("/api/v1/admin/login", auth.signIn);
        app.put("/api/v1/admin/update", [authJwt.verifyToken], auth.update);
        app.get("/api/v1/admin/getDoctor", auth.getDoctor);
        app.get("/api/v1/admin/getApprovedDoctor", auth.getApprovedDoctor);
        app.get("/api/v1/admin/getPatient", auth.getPatients);
        app.get("/api/v1/admin/getPharmacys", auth.getPharmacys);
        app.delete("/api/v1/admin/deleteUser/:id", auth.deleteUser);
        app.get("/api/v1/admin/getAllDocument", [authJwt.verifyToken], auth.getDocument);
        app.get('/api/v1/admin/getDocumentbyId/:id', authJwt.verifyToken, auth.getDocumentbyId);
        app.put('/api/v1/admin/documentApprovedreject/:id', authJwt.verifyToken, auth.documentApprovedreject);
        app.post('/api/v1/admin/addContact', authJwt.verifyToken, auth.addContact);
        app.put('/api/v1/admin/editContact/:id', authJwt.verifyToken, auth.editContact);
        app.delete('/api/v1/admin/deleteContact/:id', authJwt.verifyToken, auth.deleteContact);
        app.get('/api/v1/admin/getcontact', auth.getcontact);
        app.post("/api/v1/admin/createFaq", authJwt.verifyToken, auth.createFaq);
        app.patch("/api/v1/admin/updatefaq/:id", authJwt.verifyToken, auth.updateFaq);
        app.get("/api/v1/admin/getbyfaqId/:id", auth.getIdFaq);
        app.delete("/api/v1/admin/deleteFaq/:id", authJwt.verifyToken, auth.deleteFaq);
        app.get("/api/v1/admin/getAllFaq", auth.getFaq);
        app.post("/api/v1/admin/createCategory", authJwt.verifyToken, auth.createCategory);
        app.get("/api/v1/admin/category/:id", auth.getIdCategory);
        app.patch("/api/v1/admin/udateCategory/:id", authJwt.verifyToken, auth.updateCategory);
        app.get("/api/v1/admin/category", auth.getCategory);
        app.delete("/api/v1/admin/category/:id", authJwt.verifyToken, auth.deleteCategory);
        app.get("/api/v1/admin/subcategory/:id", auth.getIdSubCategory);
        app.get("/api/v1/admin/subcategory", auth.getSubCategory);
        app.post("/api/v1/admin/createSubcategory", authJwt.verifyToken, auth.createSubCategory);
        app.patch("/api/v1/admin/subcategory/:id", authJwt.verifyToken, auth.updateSubCategory);
        app.delete("/api/v1/admin/subcategory/:id", authJwt.verifyToken, auth.deleteSubCategory);
        app.get('/api/v1/admin/help/:id', auth.getByIdhelpandSupport);
        app.get('/api/v1/admin/help', auth.getAllHelpandSupport);
        app.delete('/api/v1/admin/deleteHelp/:id', auth.DeleteHelpandSupport);
        app.post("/api/v1/admin/addCoupan", authJwt.verifyToken, auth.addCoupan);
        app.get("/api/v1/admin/Coupan/:id", auth.getIdCoupan);
        app.patch("/api/v1/admin/Coupan/:id", authJwt.verifyToken, auth.updateCoupan);
        app.delete("/api/v1/admin/Coupan/:id", authJwt.verifyToken, auth.deleteCoupan);
        app.get("/api/v1/admin/listCoupan", authJwt.verifyToken, auth.listCoupan);
        app.post("/api/v1/admin/addCommission", authJwt.verifyToken, auth.addCommission);
        app.get("/api/v1/admin/Commission/:id", auth.getIdCommission);
        app.patch("/api/v1/admin/Commission/:id", authJwt.verifyToken, auth.updateCommission);
        app.delete("/api/v1/admin/Commission/:id", authJwt.verifyToken, auth.deleteCommission);
        app.get("/api/v1/admin/listCommission", authJwt.verifyToken, auth.listCommission);
        app.post("/api/v1/admin/createDoctorCategory", authJwt.verifyToken, auth.createDoctorCategory);
        app.get("/api/v1/admin/doctorCategory/:id", auth.getIdDoctorCategory);
        app.patch("/api/v1/admin/updateDoctorCategory/:id", authJwt.verifyToken, auth.updateDoctorCategory);
        app.get("/api/v1/admin/DoctorCategory", auth.getDoctorCategory);
        app.delete("/api/v1/admin/DoctorCategory/:id", authJwt.verifyToken, auth.deleteDoctorCategory);
        app.post("/api/v1/Blog/addBlog", [authJwt.verifyToken], auth.createBlog);
        app.get("/api/v1/Blog/all", auth.getBlog);
        app.get("/api/v1/Blog/getBlogByToken", [authJwt.verifyToken], auth.getBlogByToken);
        app.get("/api/v1/Blog/:id", auth.getIdBlog);
        app.put("/api/v1/Blog/updateBlog/:id", [authJwt.verifyToken], auth.updateBlog);
        app.delete("/api/v1/Blog/:id", [authJwt.verifyToken], auth.deleteBlog);
};