const auth = require("../controllers/adminController");
const authJwt = require("../middlewares/authJwt");
module.exports = (app) => {
        app.post("/api/v1/admin/registration", auth.registration);
        app.post("/api/v1/admin/login", auth.signIn);
        app.put("/api/v1/admin/update", [authJwt.verifyToken], auth.update);
        app.get("/api/v1/admin/getDoctor", auth.getDoctor);
        app.get("/api/v1/admin/getApprovedDoctor", auth.getApprovedDoctor);
        app.get("/api/v1/admin/getPatient", auth.getPatients);
        app.get("/api/v1/admin/getAllDocument", [authJwt.verifyToken], auth.getDocument);
        app.get('/api/v1/admin/getDocumentbyId/:id', authJwt.verifyToken, auth.getDocumentbyId);
        app.put('/api/v1/admin/documentApprovedreject/:id', authJwt.verifyToken, auth.documentApprovedreject);
        app.post('/api/v1/admin/addContact', authJwt.verifyToken, auth.addContact);
        app.put('/api/v1/admin/editContact/:id', authJwt.verifyToken, auth.editContact);
        app.delete('/api/v1/admin/deleteContact/:id', authJwt.verifyToken, auth.deleteContact);
        app.get('/api/v1/admin/getcontact', auth.getcontact);
        app.post("/api/v1/admin/createFaq", authJwt.verifyToken, auth.createFaq);
        app.patch("/api/v1/admin/updatefaq/:id", authJwt.verifyToken, auth.updateFaq);
        app.get("/api/v1/admin/getbyfaqId/:id", auth.getIdFaq);
        app.delete("/api/v1/admin/deleteFaq/:id", authJwt.verifyToken, auth.deleteFaq);
        app.get("/api/v1/admin/getAllFaq", auth.getFaq);
        app.post("/api/v1/admin/createCategory", authJwt.verifyToken, auth.createCategory);
        app.get("/api/v1/admin/category/:id", auth.getIdCategory);
        app.patch("/api/v1/admin/udateCategory/:id", authJwt.verifyToken, auth.updateCategory);
        app.get("/api/v1/admin/category", auth.getCategory);
        app.delete("/api/v1/admin/category/:id", authJwt.verifyToken, auth.deleteCategory);
        app.get("/api/v1/admin/subcategory/:id", auth.getIdSubCategory);
        app.get("/api/v1/admin/subcategory", auth.getSubCategory);
        app.post("/api/v1/admin/createSubcategory", authJwt.verifyToken, auth.createSubCategory);
        app.patch("/api/v1/admin/subcategory/:id", authJwt.verifyToken, auth.updateSubCategory);
        app.delete("/api/v1/admin/subcategory/:id", authJwt.verifyToken, auth.deleteSubCategory);
        app.get('/api/v1/admin/help/:id', auth.getByIdhelpandSupport);
        app.get('/api/v1/admin/help', auth.getAllHelpandSupport);
        app.delete('/api/v1/admin/deleteHelp/:id', auth.DeleteHelpandSupport);
};