const auth = require("../controllers/paitentsController");
const authJwt = require("../middlewares/authJwt");
const router = require('express').Router();
router.post("/registration", auth.registration);
router.post("/loginWithPhone", auth.loginWithPhone);
router.post("/:id", auth.verifyOtp);
router.put("/forgotPassword", auth.forgotPassword);
router.post("/forgotPasswordOtp/:id", auth.forgotPasswordOtp);
router.post("/resetPassword/:id", auth.resetPassword);
router.post("/resendotp/:id", auth.resendOTP);
router.put("/update", [authJwt.verifyToken], auth.update);
router.put("/changePassword", [authJwt.verifyToken], auth.changePassword);
router.post("/help/createQuery", authJwt.verifyToken, auth.AddQuery);
module.exports = router;
